# - name: Setup colorlaunch user for mosquitto
#   become: yes
#   command: mosquitto_passwd -c /etc/mosquitto/pwfile colorlaunch
#   ignore_errors: no
#   tags:
#     - mosquitto
#     - mosquitto-setup

- name: copy the mosquitto config file
  template:
    force: yes
    owner: "{{ username }}"
    src: "{{ config_dir }}/mosquitto/{{ sitename }}.conf"
    dest: /etc/mosquitto/conf.d/{{ sitename }}.conf
  become: yes
  tags:
    - mosquitto
    - mosquitto-config

- name: copy the mosquitto acl config file
  template:
    force: yes
    owner: "mosquitto"
    group: "mosquitto"
    src: "{{ config_dir }}/mosquitto/{{ sitename }}.acl"
    dest: /etc/mosquitto/{{ sitename }}.acl
  become: yes
  tags:
    - mosquitto
    - mosquitto-config

- name: Restart the mosquitto service
  become: yes
  command: systemctl restart mosquitto
  ignore_errors: yes
  tags:
    - mosquitto
    - mosquitto-config
