---
- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - python3
  - python3-apt
  - apt-transport-https
#  - fail2ban
  - git-core
  - ufw
  - curl
  tags:
    - deps
