---
- name: Create Repo Directory
  file: path={{repoDir}} state=directory
  tags: [app, git]

- name: Git Clone Repo
  git: repo={{repo}} dest={{repoDir}} update=yes force=yes
  register: git_finished
  tags: [app, git]
