- name: copy the nginx config file and restart nginx
  template:
    force: yes
    owner: "{{ username }}"
    group: www-data
    src: "{{ config_dir }}/{{ sitename }}/{{ sitename }}.conf"
    dest: /etc/nginx/conf.d/{{ sitename }}.conf
  become: yes
  tags: [site, nginx]

- name: create project directories
  become: yes
  file:
    path: "{{ htdocs_dir }}"
    state: directory
    owner: "{{ username }}"
    group: www-data
    mode: 0775
  tags: [site, nginx]

- name: Apply www directory permissions
  become: yes
  file:
    path: "{{ htdocs_dir }}"
    state: directory
    group: www-data
    mode: '1775'
    recurse: yes
  tags: [site, nginx]

- name: copy the content of the web site
  synchronize:
    delete: yes
    archive: no
    recursive: yes
    src: "{{ htdocs_src }}/"
    dest: "{{ htdocs_dir }}"
  tags: [site, nginx]
  when: should_sync_local

- name: Re-set htdocs group
  become: yes
  file:
    path: "{{ htdocs_dir }}"
    state: directory
    group: www-data
    mode: '1775'
    recurse: yes
  tags: [site, nginx]

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
  tags: [site, nginx]
